server:
  port: 8907
  servlet:
    context-path: /us-svc
spring:
  datasource:
    url: jdbc:postgresql://10.10.2.92:5432/postgres
    username: postgres
    password: PPU.P4ssw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: Users_Security
        dialect: org.hibernate.dialect.PostgreSQLDialect